// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBOvpek_PLxAuBL4NBZZAQEvtgob2WwnM',
    appId: '1:955350383276:web:c51169136a90539a9efd09',
    messagingSenderId: '955350383276',
    projectId: 'wabebe-ff35c',
    authDomain: 'wabebe-ff35c.firebaseapp.com',
    storageBucket: 'wabebe-ff35c.appspot.com',
    measurementId: 'G-JS0WS4YN0Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALivJxFrVN9e_SEqO21TMC-ccy3rrZmw8',
    appId: '1:955350383276:android:a9761081527201699efd09',
    messagingSenderId: '955350383276',
    projectId: 'wabebe-ff35c',
    storageBucket: 'wabebe-ff35c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDn1sfr5UdmnAJTTljU2PWbYmoq6GNrldY',
    appId: '1:955350383276:ios:18af60590e55ba379efd09',
    messagingSenderId: '955350383276',
    projectId: 'wabebe-ff35c',
    storageBucket: 'wabebe-ff35c.appspot.com',
    iosClientId: '955350383276-vaviob8ojoeti837qhhe0h5equcr4jmp.apps.googleusercontent.com',
    iosBundleId: 'com.mginc.wabebe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDn1sfr5UdmnAJTTljU2PWbYmoq6GNrldY',
    appId: '1:955350383276:ios:18af60590e55ba379efd09',
    messagingSenderId: '955350383276',
    projectId: 'wabebe-ff35c',
    storageBucket: 'wabebe-ff35c.appspot.com',
    iosClientId: '955350383276-vaviob8ojoeti837qhhe0h5equcr4jmp.apps.googleusercontent.com',
    iosBundleId: 'com.mginc.wabebe',
  );
}
